function cfg = plel_hardware_config()
%PLEL_HARDWARE_CONFIG Single traceable pre-fabrication hardware baseline.
% Source requirements are from docs/source/design-source.pdf. A TBD field is
% intentionally not treated as a verified hardware fact.
    cfg.source = 'docs/source/design-source.pdf';
    cfg.provenance = struct('PDF','FROZEN_FROM_PDF','DATASHEET','DATASHEET', ...
        'CALCULATED','CALCULATED','TARGET','DESIGN_TARGET','TBD','TBD');
    cfg.operating = struct('vin_min_V',10,'vin_max_V',15,'imax_A',2, ...
        'pmax_W',30,'pcontinuous_target_W',24,'mosfet_count',4, ...
        'shunt_ohm',0.01,'shunt_tolerance',0.01,'ballast_ohm',0.1, ...
        'ballast_power_W',3,'gate_ohm',1000,'pulldown_ohm',100000, ...
        'gate_zener_V',8.2,'ambient_example_C',35);
    cfg.parts = struct( ...
        'mosfet_mpn','BUZ11','mosfet_manufacturer','TBD', ...
        'sense_mpn','INA180A3IDBVR','sense_package','SOT-23-5 DBV', ...
        'dac_mpn','MCP4725A0T-E/CH','dac_package','SOT-23-6 CH', ...
        'opamp_mpn','LM358BIDR','opamp_package','SOIC-8 D', ...
        'mcu_mpn','ESP32-WROOM-32','ldo5_mpn','L7805','ldo33_mpn','TBD', ...
        'shunt_mpn','TBD','ballast_mpn','TBD','heatsink_mpn','TBD', ...
        'fan_mpn','TBD','fuse_mpn','TBD','connector_mpn','TBD');
    cfg.datasheet = struct('sense_offset_max_uV',500,'sense_gain_error',0.01, ...
        'sense_gain_drift_per_C',20e-6,'sense_bandwidth_Hz',150e3, ...
        'mosfet_rthetaJC_K_W',1.67,'mosfet_tjmax_C',175, ...
        'mosfet_ciss_min_pF',1500,'mosfet_ciss_max_pF',2000, ...
        'lm_gbw_Hz',1.2e6,'lm_slew_V_s',0.5,'lm_supply_min_V',3, ...
        'mcp_supply_min_V',2.7,'mcp_supply_max_V',5.5, ...
        'mcp_supply_current_max_A',400e-6);
    cfg.thermal = struct('rsa_target_K_W',1.5,'rcs_design_K_W',0.5, ...
        'sink_target_C',80,'junction_target_C',100);
    cfg.pcb = struct('copper_oz',2,'copper_thickness_m',70e-6, ...
        'trace_length_m',0.1,'trace_width_example_m',0.005, ...
        'allowed_trace_rise_C',10,'power_trace_target_mm',1.0, ...
        'kelvin_required',true);
    cfg.status = struct('exact_bom_complete',false, ...
        'mosfet_soa_hot_case_qualified',false,'heatsink_selected',false, ...
        'adc_calibrated',false,'gate_drive_validated',false, ...
        'loop_stability_validated',false,'startup_inhibit_defined',false, ...
        'fault_latch_defined',false,'footprints_verified',false);
end
