function map = plel_r1_gpio_map()
%PLEL_R1_GPIO_MAP Deterministic ESP32-WROOM-32E R1 assignment.
    map = struct('i2c_sda',21,'i2c_scl',22,'adc_current',35,'adc_voltage',34, ...
        'adc_ntc',39,'fan_control',26,'fault_input',27,'web_run_enable',25, ...
        'estop_monitor',33,'service_uart_tx',1,'service_uart_rx',3, ...
        'boot_gpio',0,'reset_pin','EN','freed_from_r0',{{18,19,23}});
end
