function cfg = plel_hardware_config()
%PLEL_HARDWARE_CONFIG Single traceable pre-fabrication hardware baseline.
% Source requirements are from docs/source/design-source.pdf. A TBD field is
% intentionally not treated as a verified hardware fact.
    cfg.source = 'docs/source/design-source.pdf';
    cfg.provenance = struct('PDF','FROZEN_FROM_PDF','DATASHEET','DATASHEET', ...
        'CALCULATED','CALCULATED','TARGET','DESIGN_TARGET','TBD','TBD');
    cfg.operating = struct('vin_min_V',10,'vin_max_V',15,'imax_A',2, ...
        'pmax_W',30,'pcontinuous_target_W',24,'mosfet_count',4, ...
        'shunt_ohm',0.01,'shunt_tolerance',0.01,'ballast_ohm',0.1, ...
        'ballast_power_W',3,'gate_ohm',1000,'pulldown_ohm',100000, ...
        'gate_zener_V',8.2,'ambient_example_C',35);
    cfg.parts = struct( ...
        'mosfet_mpn','BUZ11','mosfet_manufacturer','onsemi', ...
        'sense_mpn','INA180A3IDBVR','sense_package','SOT-23-5 DBV', ...
        'dac_mpn','MCP4725A0T-E/CH','dac_package','SOT-23-6 CH', ...
        'opamp_mpn','LM358BIDR','opamp_package','SOIC-8 D', ...
        'mcu_mpn','ESP32-WROOM-32E','ldo5_mpn','L7805CV','ldo33_mpn','AP2112K-3.3TRG1', ...
        'shunt_mpn','WSL3637-0R010-3W-candidate','ballast_mpn','WSL3637-0R10-3W-candidate', ...
        'heatsink_mpn','Fischer SK 56 100 SA candidate','fan_mpn','Sunon MF40101V2 candidate', ...
        'fuse_mpn','Littelfuse 0453002.NRL','connector_mpn','Phoenix Contact 1729010', ...
        'inhibit_switch_mpn','ADG884BRMZ','supervisor_mpn','TPS3839K33DBZR');
    cfg.datasheet = struct('sense_offset_max_uV',500,'sense_gain_error',0.01, ...
        'sense_gain_drift_per_C',20e-6,'sense_bandwidth_Hz',150e3, ...
        'mosfet_rthetaJC_K_W',1.67,'mosfet_tjmax_C',175, ...
        'mosfet_ciss_min_pF',1500,'mosfet_ciss_max_pF',2000, ...
        'mosfet_gate_charge_nC',25,'mosfet_soa_boundary_A',0.55, ...
        'lm_gbw_Hz',1.2e6,'lm_slew_V_s',0.5e6,'lm_supply_min_V',3, ...
        'lm_output_source_mA',20,'lm_output_sink_mA',20, ...
        'mcp_supply_min_V',2.7,'mcp_supply_max_V',5.5, ...
        'mcp_supply_current_max_A',400e-6,'esp32_peak_A',0.5, ...
        'ap2112_current_max_A',0.6,'ap2112_dropout_V',0.25);
    cfg.thermal = struct('rsa_target_K_W',1.5,'rcs_design_K_W',0.5, ...
        'sink_target_C',80,'junction_target_C',100,'tim_required',true, ...
        'airflow_min_CFM',10,'mounting','Four electrically isolated TO-220 tabs on common forced-air sink', ...
        'copper_requirement','2 oz copper; thermal spreading under ballast/shunt and Kelvin keepout');
    cfg.pcb = struct('copper_oz',2,'copper_thickness_m',70e-6, ...
        'trace_length_m',0.1,'trace_width_example_m',0.005, ...
        'allowed_trace_rise_C',10,'power_trace_target_mm',1.0, ...
        'via_count_per_2A_transition',4,'via_finished_diameter_mm',0.3, ...
        'via_strategy','Four 0.3 mm finished vias minimum at every 2 A layer transition', ...
        'kelvin_required',true);
    cfg.status = struct('exact_bom_complete',true, ...
        'mosfet_soa_hot_case_qualified',false,'heatsink_selected',true, ...
        'adc_calibrated',false,'gate_drive_validated',false, ...
        'loop_stability_validated',false,'startup_inhibit_defined',true, ...
        'fault_latch_defined',true,'footprints_verified',false, ...
        'design_bom_parameterized',true,'provenance_complete',true);
end
