function status = hardware_validation_status()
%HARDWARE_VALIDATION_STATUS Separate simulation/datasheet closure from hardware evidence.
    status=struct('PCB_DESIGN_RELEASE','PASS','HARDWARE_VALIDATION','PENDING', ...
        'HARDWARE_VALIDATION_SIMULATION','COMPLETE', ...
        'items',struct( ...
        'current_sharing','SIMULATION_CLOSED', ...
        'soa_hot_case','PHYSICAL_TEST_REQUIRED', ...
        'thermal_assembly','PHYSICAL_TEST_REQUIRED', ...
        'current_sense','DATASHEET_CLOSED', ...
        'adc_calibration','PHYSICAL_TEST_REQUIRED', ...
        'gate_waveform','PHYSICAL_TEST_REQUIRED', ...
        'loop_response','PHYSICAL_TEST_REQUIRED', ...
        'startup_brownout_fault','PHYSICAL_TEST_REQUIRED', ...
        'emergency_stop','PHYSICAL_TEST_REQUIRED', ...
        'communication_timeout','SIMULATION_CLOSED', ...
        'power_tree_temperature','PHYSICAL_TEST_REQUIRED'), ...
        'provenance_policy','SIMULATION_CLOSED is never MEASURED or CALIBRATED');
end
