function out = plel_r1_soa_twin(cfg)
%PLEL_R1_SOA_TWIN Map operating points against documented conservative boundary.
% The BUZ11 curve is graphical; this function does not invent a full curve.
    v=linspace(cfg.operating.vin_min_V,cfg.operating.vin_max_V,51);
    i=linspace(0.1,cfg.operating.imax_A,51); [V,I]=meshgrid(v,i);
    branch=I/cfg.operating.mosfet_count; vds=V-I*cfg.operating.shunt_ohm-branch*cfg.operating.ballast_ohm;
    p=vds.*branch; boundary=cfg.datasheet.mosfet_soa_boundary_A; margin=boundary-branch;
    out=struct('vin_V',v,'total_current_A',i,'vds_V',vds,'id_per_device_A',branch, ...
        'power_per_device_W',p,'conservative_soa_boundary_A',boundary, ...
        'margin_A',margin,'worst_margin_A',min(margin(:)), ...
        'case_temperature_C',25,'extraction_uncertainty_A',0.05, ...
        'limitation','Graphical DC SOA extraction at 25 C only; no unmeasured temperature curve invented', ...
        'provenance','SIMULATED/DATASHEET/CALCULATED; hot-case qualification pending');
end
