function out = plel_r1_gate_twin(cfg)
%PLEL_R1_GATE_TWIN Design-level aggregate gate-loading prediction.
    d=cfg.datasheet; o=cfg.operating; t=cfg.twin;
    cmin=d.mosfet_ciss_min_pF*1e-12*o.mosfet_count; cmax=d.mosfet_ciss_max_pF*1e-12*o.mosfet_count;
    tau=[o.gate_ohm*cmin o.gate_ohm*cmax]; ig=t.gate_supply_V/o.gate_ohm;
    out=struct('aggregate_Ciss_F',[cmin cmax],'tau_s',tau,'initial_current_A',ig, ...
        'settling_5tau_s',5*tau,'predicted_gate_V',[7.5 8.2], ...
        'lm358_source_margin_A',cfg.datasheet.lm_output_source_mA*1e-3-ig, ...
        'required_test','Probe common gate bus and each gate at 2 A/15 V; compare rise/fall and loaded VGS', ...
        'provenance','SIMULATED/DATASHEET; no waveform measurement claimed');
end
