function out = plel_r1_adc_calibration_model(cfg)
%PLEL_R1_ADC_CALIBRATION_MODEL Define, but do not populate, two-point ADC calibration.
    out=struct('channels',{{'current_ADC','voltage_ADC','ntc_ADC'}}, ...
      'raw_code_equation','raw = round((quantity/fullscale)*(2^bits-1)*gain + offset)', ...
      'calibration_equation','quantity_corrected = slope*raw + intercept', ...
      'points_required','At least zero and a traceable nonzero reference for each channel; current uses 0, 0.5, 2 A', ...
      'coefficients',struct('slope',NaN,'intercept',NaN), ...
      'status','PHYSICAL_TEST_REQUIRED','provenance','DESIGN_TARGET; coefficients intentionally absent');
end
