function out = plel_r1_communication_twin(cfg, loss_s)
%PLEL_R1_COMMUNICATION_TWIN Simulate supervisory heartbeat timeout.
    if nargin<2, loss_s=[1 2 3 10]; end
    out=struct('loss_s',loss_s,'timeout_s',cfg.product.communication_timeout_s, ...
        'communication_fault',loss_s>=cfg.product.communication_timeout_s, ...
        'command_zero',loss_s>=cfg.product.communication_timeout_s, ...
        'power_stage_disabled',loss_s>=cfg.product.communication_timeout_s, ...
        'provenance','SIMULATED/DESIGN_TARGET; firmware and timing hardware test pending');
end
