function out = plel_r1_monte_carlo(cfg)
%PLEL_R1_MONTE_CARLO Correlatable system uncertainty summary.
    sh=plel_r1_current_sharing(cfg,cfg.twin.mc_trials);
    se=plel_r1_sense_twin(cfg,cfg.twin.mc_trials);
    th=plel_r1_thermal_twin(cfg,mean(sh.branch_power_W,1),cfg.operating.ambient_example_C);
    out=struct('trials',cfg.twin.mc_trials,'sharing',sh.summary, ...
        'worst_branch_power_summary',stats(sh.worst_branch_power_W), ...
        'current_sense_mean_A',se.mean_A,'current_sense_std_A',se.std_A, ...
        'junction_C',th.junction_C,'thermal_margin_C',th.margin_C, ...
        'outlier_policy','Report min/max and percentiles; do not discard trials', ...
        'provenance','SIMULATED; distributions are design assumptions, not measured matching');
end
function s=stats(x), s=struct('mean',mean(x),'std',std(x),'min',min(x),'max',max(x),'p1',prctile(x,1),'p99',prctile(x,99)); end
