function out = plel_r1_gate_twin(cfg)
%PLEL_R1_GATE_TWIN Four parallel R-C branches, not one R with summed C.
% A step-current demand and a slew-limited demand are alternative bounds;
% adding them double-counts the same charging current. Ciss is a scenario
% envelope at the datasheet test point, not a guaranteed nonlinear gate model.
    d=cfg.datasheet; o=cfg.operating;
    n=o.mosfet_count; R=o.gate_ohm; Rpd=o.pulldown_ohm;
    C=[d.mosfet_ciss_min_pF d.mosfet_ciss_max_pF]*1e-12;
    req=1/(1/R+1/Rpd);
    tau=req*C;
    step_V=o.gate_zener_V;
    step_demand=n*step_V/R;
    slew_demand=n*C*d.lm_slew_V_s;
    dc_load=n*step_V/(R+Rpd);
    out=struct('branch_count',n,'aggregate_Ciss_F',n*C, ...
        'branch_Ciss_F',C,'tau_s',tau,'initial_current_A',step_demand, ...
        'slew_charging_current_A',slew_demand,'pulldown_dc_current_A',dc_load, ...
        'settling_5tau_s',5*tau,'gate_off_5tau_s',5*Rpd*C, ...
        'predicted_gate_V',[],'step_test_V',step_V, ...
        'lm358_source_margin_A',d.lm_output_source_mA*1e-3-step_demand, ...
        'current_limit_basis','Configured 20 mA is not a guaranteed full-swing source rating', ...
        'required_test','Nonlinear gate waveform and current sharing; model does not establish output headroom', ...
        'provenance','CALCULATED scenario; no waveform measurement or operating VGS claimed');
end
