function result = validate_web_interface_r1(cfg)
%VALIDATE_WEB_INTERFACE_R1 Validate the product-level web contract.
    expected={'GET /api/status','GET /api/config','POST /api/mode','POST /api/setpoint', ...
        'POST /api/start','POST /api/stop','POST /api/reset','GET /api/test/status','GET /api/test/data'};
    pass=isequal(cfg.product.web_endpoints,expected) && strcmp(cfg.product.websocket_endpoint,'/ws') && ...
        cfg.product.communication_timeout_s > 0;
    value=struct('transport','local ESP32 Wi-Fi, no cloud','endpoints',{expected}, ...
        'websocket',cfg.product.websocket_endpoint,'communication_timeout_s',cfg.product.communication_timeout_s, ...
        'safety_boundary','web interface cannot bypass validator, state machine, or hardware E-stop');
    if pass, s='PASS'; else, s='BLOCKED'; end
    result=plel_validation_result('PLEL R1 web-control interface',s,value,true,true, ...
        'DESIGN_TARGET','docs/WEB_INTERFACE_ARCHITECTURE_R1.md; firmware implementation remains future work',false, ...
        'Interface contract closed for PCB and firmware integration');
end
