function report = validate_pcb_design_release()
%VALIDATE_PCB_DESIGN_RELEASE Execute all pre-fabrication baseline checks.
% Physical validation is reported separately and is never inferred from MATLAB.
    cfg=plel_hardware_config();
    checks={validate_source_mapping(cfg),validate_product_r1(cfg),validate_web_interface_r1(cfg), ...
        validate_gpio_map_r1(cfg),validate_bom(cfg),validate_power_stage(cfg),validate_soa(cfg), ...
        validate_thermal(cfg),validate_current_sense(cfg),validate_gate_drive(cfg), ...
        validate_loop_design(cfg),validate_power_tree(cfg),validate_startup_safety(cfg), ...
        validate_pcb_current_paths(cfg),validate_footprints(cfg)};
    % Never infer topology closure from the absence of a BLOCKED string.
    % FAIL, unknown states, missing evidence, and unaccepted assumptions block.
    release=plel_release_decision(checks);
    hardware_items={'actual MOSFET current sharing','hot-case DC SOA behavior', ...
        'assembled heatsink/TIM/airflow thermal resistance','current-sense and ADC calibration', ...
        'loaded gate waveform','physical loop response','startup transients and brownout', ...
        'fault response','regulator temperature','final PCB DFM and production inspection'};
    report=struct('PCB_DESIGN_RELEASE',release,'HARDWARE_VALIDATION','PENDING', ...
        'PRE_FABRICATION_DESIGN_RELEASE',release, ...
        'source',cfg.source,'checks',{checks}, ...
        'hardware_validation_items',{hardware_items}, ...
        'note','PASS closes the design baseline only; hardware validation remains pending and is never inferred from MATLAB.');
end
