function result = validate_startup_safety(cfg)
%VALIDATE_STARTUP_SAFETY Require an actual hardware inhibit topology.
    value=struct('MCP4725_por','EEPROM value/midscale per DS22039D', ...
        'required_safe_states',{{'MCU OFF','RESET','BOOT','BROWNOUT','FAULT'}}, ...
        'inhibit_topology',cfg.status.startup_inhibit_defined);
    result=plel_validation_result('Startup and hardware power-stage inhibit','BLOCKED',value, ...
        'Implemented circuit forcing control node OFF in all safe states',NaN,'DATASHEET/TBD', ...
        'Microchip DS22039D §5.4; firmware zero is not hardware proof',true, ...
        'Schematic topology and fault-state analysis required');
end
