function result = validate_source_mapping(cfg)
%VALIDATE_SOURCE_MAPPING Confirm the released baseline explicitly maps source sections.
    sections={'8 input/interface','9 architecture','10 power balance','11-15 sensing/control', ...
        '16-21 MOSFET/thermal/gate','22-26 commands/protection','27-30 rails/UI', ...
        '31-34 protection/PCB'};
    value=struct('source',cfg.source,'mapped_sections',{sections}, ...
        'mapping_document','docs/PCB_DESIGN_REQUIREMENTS.md and data/pcb_design_bom.json');
    result=plel_validation_result('Source-PDF requirements mapped','PASS',value,true,true, ...
        'FROZEN_FROM_PDF','Source PDF remains authoritative; design clarifications are explicitly documented',false, ...
        'No source requirement silently replaced');
end
