function result = validate_pcb_current_paths(cfg)
%VALIDATE_PCB_CURRENT_PATHS Calculate trace ampacity and source-example resistance.
    p=cfg.pcb; I=cfg.operating.imax_A;
    area_mil2=(I/(0.048*p.allowed_trace_rise_C^0.44))^(1/0.725);
    width_mm=(area_mil2/2.8)*0.0254;
    R=1.724e-8*p.trace_length_m/(p.trace_width_example_m*p.copper_thickness_m);
    value=struct('copper_thickness_m',p.copper_thickness_m, ...
        'ipc2221_min_external_width_mm',width_mm,'design_target_width_mm',p.power_trace_target_mm, ...
        'source_example_R_ohm',R,'source_example_drop_V',I*R,'source_example_loss_W',I^2*R, ...
        'via_strategy','TBD fabricator stackup/current data','kelvin_required',p.kelvin_required);
    result=plel_validation_result('PCB current paths','CONDITIONAL',value, ...
        'Final stackup, via and voltage-drop constraints',NaN,'CALCULATED/DESIGN_TARGET', ...
        'Source §§32–33; IPC-2221 empirical check documented in closure function',false, ...
        'Final fabrication stackup and via strategy required');
end
