function result = validate_soa(cfg)
%VALIDATE_SOA Evaluate the operating point without claiming hot-case qualification.
    o=cfg.operating; ib=o.imax_A/o.mosfet_count;
    vds=o.vin_max_V-o.imax_A*o.shunt_ohm-ib*o.ballast_ohm;
    p=vds*ib;
    value=struct('Vds_V',vds,'Id_A',ib,'Pdevice_W',p,'case_temperature_C',25, ...
        'boundary_A',NaN,'margin',NaN,'duration','DC curve candidate only');
    result=plel_validation_result('BUZ11 DC forward-bias SOA','CONDITIONAL',value, ...
        'Exact device DC SOA at actual Tc/duration',NaN,'DATASHEET', ...
        'onsemi BUZ11/D candidate Figure 4; candidate is not exact purchased lot',true, ...
        'SOA and exact manufacturer/lot remain release blockers');
end
