function result = validate_startup_safety(cfg)
%VALIDATE_STARTUP_SAFETY Separate required logic from implemented connectivity.
% Active-low RESET_n is low on reset and high when healthy: no inverter
% belongs between a conventional RESET_n output and positive RESET_OK.
    inputs=dec2bin(0:15,4)-'0';
    enable=inputs(:,1)&inputs(:,2)&inputs(:,3)&~inputs(:,4);
    value=struct('input_order',{{'ESTOP_OK','MCU_RUN','RESET_OK','FAULT'}}, ...
        'truth_table',[inputs double(enable)], ...
        'enable_logic','ESTOP_OK AND MCU_RUN AND RESET_OK AND NOT FAULT', ...
        'reset_polarity','RESET_n low during reset; high when healthy; do not invert', ...
        'MCP4725_por','EEPROM startup value does not establish safe current', ...
        'inhibit_switch_mpn',cfg.parts.inhibit_switch_mpn, ...
        'implemented_connectivity_verified',false);
    result=plel_validation_result('Startup and hardware power-stage inhibit','BLOCKED',value, ...
        true,false,'REQUIREMENT_ONLY', ...
        'Boolean requirement enumerated; no approved pin-level hardware implementation or startup power-sequence proof exists',true, ...
        'Do not infer hardware safety from a Boolean truth table or a cfg.status flag');
end
