function result = validate_footprints(cfg)
%VALIDATE_FOOTPRINTS Require exact mechanical drawings before release.
    value=struct('critical_packages',{{cfg.parts.sense_package,cfg.parts.dac_package,cfg.parts.opamp_package,'ESP32-WROOM-32E module','TO-220AB','WSL3637 power resistor','Phoenix 1729010'}}, ...
        'verified',cfg.status.footprints_verified,'review_status','FOOTPRINT_REVIEW_REQUIRED', ...
        'rules','Use manufacturer land patterns; pin-1 marks and antenna keepout on assembly drawing; no generic substitution');
    result=plel_validation_result('Critical footprints and land patterns','CONDITIONAL',value, ...
        true,true,'DATASHEET/DESIGN_TARGET','Exact package choices are defined; final CAD-library drawing check is a pre-fabrication review, not hardware validation',false, ...
        'No unresolved safety-critical package choice; complete library review before Gerbers');
end
