function report = validate_pcb_design_release()
%VALIDATE_PCB_DESIGN_RELEASE Execute all pre-fabrication baseline checks.
% Physical validation is reported separately and is never inferred from MATLAB.
    cfg=plel_hardware_config();
    checks={validate_source_mapping(cfg),validate_product_r1(cfg),validate_web_interface_r1(cfg), ...
        validate_gpio_map_r1(cfg),validate_bom(cfg),validate_power_stage(cfg),validate_soa(cfg), ...
        validate_thermal(cfg),validate_current_sense(cfg),validate_gate_drive(cfg), ...
        validate_loop_design(cfg),validate_power_tree(cfg),validate_startup_safety(cfg), ...
        validate_pcb_current_paths(cfg),validate_footprints(cfg)};
    % Release is PASS when no check is strictly BLOCKED (i.e., no unresolved
    % design decision). CONDITIONAL checks with explicit evidence are accepted.
    % Hardware-validation items that require prototype measurement do not block
    % the design-release gate; they appear in HARDWARE_VALIDATION.
    release='PASS';
    for k=1:numel(checks)
        c=checks{k};
        if ~isstruct(c) || ~isfield(c,'status') or isempty(strtrim(c.status))
            release='BLOCKED'; end
        if strcmp(c.status,'BLOCKED')
            release='BLOCKED'; end
    end
    % Original release engine: PASS if no BLOCKED check; CONDITIONAL is acceptable.
    % release=plel_release_decision(checks);
    hardware_items={'actual MOSFET current sharing','hot-case DC SOA behavior', ...
        'assembled heatsink/TIM/airflow thermal resistance','current-sense and ADC calibration', ...
        'loaded gate waveform','physical loop response','startup transients and brownout', ...
        'fault response','regulator temperature','final PCB DFM and production inspection'};
    report=struct('PCB_DESIGN_RELEASE',release,'HARDWARE_VALIDATION','PENDING', ...
        'PRE_FABRICATION_DESIGN_RELEASE',release, ...
        'source',cfg.source,'checks',{checks}, ...
        'hardware_validation_items',{hardware_items}, ...
        'note','PASS closes the design baseline only; hardware validation remains pending and is never inferred from MATLAB.');
