function result = validate_current_sense(cfg)
%VALIDATE_CURRENT_SENSE Calculate datasheet-bounded uncalibrated error.
    I=[0.1 0.5 1 1.5 2]; o=cfg.operating; d=cfg.datasheet;
    offset_A=d.sense_offset_max_uV*1e-6/(o.shunt_ohm*100);
    gain_fraction=o.shunt_tolerance+d.sense_gain_error;
    abs_err=I*gain_fraction+offset_A;
    pct=100*abs_err./I;
    value=struct('current_A',I,'nominal_Vsense_V',I, ...
        'worst_case_partial_error_A',abs_err,'worst_case_partial_error_percent',pct, ...
        'excluded_terms','shunt TCR, ESP32 ADC transfer, Kelvin/layout and temperature calibration');
    result=plel_validation_result('Current-sense error budget','CONDITIONAL',value, ...
        'Complete error budget including ADC/TCR/layout',NaN,'DATASHEET/CALCULATED', ...
        'TI SBOS741H plus source shunt tolerance; partial bound only',true, ...
        'Calibration and ADC/layout terms required before accuracy claim');
end
