function result = validate_gate_drive(cfg)
%VALIDATE_GATE_DRIVE Bound the gate-drive load; do not infer operating VGS from VGS(th).
    d=cfg.datasheet; o=cfg.operating;
    c_total_min=d.mosfet_ciss_min_pF*1e-12*o.mosfet_count;
    c_total_max=d.mosfet_ciss_max_pF*1e-12*o.mosfet_count;
    tau_min=o.gate_ohm*c_total_min; tau_max=o.gate_ohm*c_total_max;
    value=struct('aggregate_Ciss_min_F',c_total_min,'aggregate_Ciss_max_F',c_total_max, ...
        'gate_network_tau_min_s',tau_min,'gate_network_tau_max_s',tau_max, ...
        'LM358_slew_V_per_us',d.lm_slew_V_s/1e6,'required_operating_Vgs','TBD');
    result=plel_validation_result('LM358B four-device gate drive','BLOCKED',value, ...
        'Required operating VGS and loaded LM358B swing/current',NaN,'DATASHEET/CALCULATED', ...
        'BUZ11 candidate Ciss range and LM358B datasheet; Ciss is not full assembled plant model',true, ...
        'Gate-drive DC/dynamic feasibility requires exact device and loaded test/model');
end
