function result = validate_footprints(cfg)
%VALIDATE_FOOTPRINTS Require exact mechanical drawings before release.
    value=struct('critical_packages',{{cfg.parts.sense_package,cfg.parts.dac_package,cfg.parts.opamp_package,'ESP32 module','TO-220','shunt','connectors'}}, ...
        'verified',cfg.status.footprints_verified);
    result=plel_validation_result('Critical footprints and land patterns','BLOCKED',value, ...
        true,false,'TBD','Exact manufacturer drawings and PCB library review',false, ...
        'No generic footprint is accepted for release');
end
