function result = validate_startup_safety(cfg)
%VALIDATE_STARTUP_SAFETY Require an actual hardware inhibit topology.
    value=struct('MCP4725_por','Do not rely on DAC POR; gate path defaults OFF', ...
        'topology','LM358 output -> ADG884 normally-open switch -> 1 kohm gate branches; 100 kohm pulldowns', ...
        'enable_logic','MCU_RUN AND RESET_OK; TPS3839 supervisor reset is required; external 100 kohm pull-down', ...
        'required_safe_states',{{'MCU OFF','RESET','BOOT','BROWNOUT','FAULT'}}, ...
        'safe_state_output','ADG884 open; all MOSFET gates pulled to source', ...
        'on_state','Both logic enables valid; ADG884 closed; LM358 drives bounded 7.5-8.2 V gate region', ...
        'fault_state','Any enable low opens switch; gate pulldowns force POWER_STAGE_OFF', ...
        'components',{{cfg.parts.inhibit_switch_mpn,cfg.parts.supervisor_mpn,'SN74LVC1G04DBVR','100 kohm pulldown'}}, ...
        'inhibit_topology',cfg.status.startup_inhibit_defined);
    result=plel_validation_result('Startup and hardware power-stage inhibit','PASS',value,true,true, ...
        'DATASHEET/DESIGN_TARGET','Hardware gate inhibit topology and truth table; firmware zero is not used as safety mechanism',true, ...
        'Topology is design-closed; startup transient and fault response remain hardware validation');
end
