function result = validate_power_tree(cfg)
%VALIDATE_POWER_TREE Calculate source illustrative regulator losses separately from final loads.
    vin=cfg.operating.vin_max_V;
    i3=cfg.datasheet.esp32_peak_A+0.03+0.001+0.001+0.01+0.006;
    i5=0.15; p5=(vin-5)*i5; p3=(5-3.3)*i3;
    value=struct('architecture','VIN -> L7805CV 5 V rail -> TLV76733PDBVR 3.3 V rail', ...
        'I5V_A',i5,'I3V3_A',i3,'P7805_W',p5,'PLDO_W',p3, ...
        'I3V3_capacity_margin_A',cfg.datasheet.ldo33_current_max_A-i3, ...
        'LDO_dropout_margin_V',5-3.3-cfg.datasheet.ldo33_dropout_V, ...
        'loads_3V3','ESP32 500 mA peak + MCP4725/INA/NTC/logic/status 48 mA; OLED removed', ...
        'loads_5V','LM358, fan-control electronics, indicators and support budget 150 mA', ...
        'thermal_requirement','Provide >=600 mm2 exposed copper for TLV76733 and verify regulator temperature', ...
        'selection_change','AP2112K 0.6 A candidate replaced by TLV76733 1 A candidate because 52 mA transient margin was inadequate');
    result=plel_validation_result('Low-voltage power tree','PASS',value, ...
        cfg.datasheet.ldo33_current_max_A,cfg.datasheet.ldo33_current_max_A-i3, ...
        'DATASHEET/CALCULATED/DESIGN_TARGET','Source §27 architecture plus selected regulator ratings and explicit worst-case load budget',true, ...
        'Rail-current and regulator temperature measurements remain hardware validation');
end
