function result = validate_gate_drive(cfg)
%VALIDATE_GATE_DRIVE Bound the gate-drive load; do not infer operating VGS from VGS(th).
    d=cfg.datasheet; o=cfg.operating;
    c_total_min=d.mosfet_ciss_min_pF*1e-12*o.mosfet_count;
    c_total_max=d.mosfet_ciss_max_pF*1e-12*o.mosfet_count;
    tau_min=o.gate_ohm*c_total_min; tau_max=o.gate_ohm*c_total_max;
    vgs_min=7.5; vgs_max=8.2; gate_current_max=vgs_max/o.gate_ohm;
    value=struct('aggregate_Ciss_min_F',c_total_min,'aggregate_Ciss_max_F',c_total_max, ...
        'gate_network_tau_min_s',tau_min,'gate_network_tau_max_s',tau_max, ...
        'LM358_slew_V_per_us',d.lm_slew_V_s/1e6,'design_Vgs_min_V',vgs_min, ...
        'design_Vgs_max_V',vgs_max,'initial_gate_current_A',gate_current_max, ...
        'LM358_source_margin_mA',d.lm_output_source_mA*1e-3-gate_current_max, ...
        'gate_clamp','8.2 V zener per branch');
    result=plel_validation_result('LM358B four-device gate drive','CONDITIONAL',value, ...
        d.lm_output_source_mA*1e-3, d.lm_output_source_mA*1e-3-gate_current_max, ...
        'DATASHEET/CALCULATED','BUZ11 Ciss/charge candidate and LM358B datasheet; 1 kohm branch network',true, ...
        'Design region closed; loaded gate waveform and sharing remain hardware validation');
end
