function result = validate_product_r1(cfg)
%VALIDATE_PRODUCT_R1 Validate the frozen R1 product interface definition.
    pass=strcmp(cfg.product.revision,'PLEL R1') && ~cfg.product.oled_fitted && ...
        ~cfg.product.encoder_fitted && ~cfg.product.ordinary_buttons_fitted && ...
        cfg.product.emergency_stop_fitted && ~cfg.product.cloud_enabled;
    if pass, s='PASS'; else, s='BLOCKED'; end
    value=struct('revision',cfg.product.revision,'interface',cfg.product.interface, ...
        'oled_fitted',cfg.product.oled_fitted,'encoder_fitted',cfg.product.encoder_fitted, ...
        'ordinary_buttons_fitted',cfg.product.ordinary_buttons_fitted,'emergency_stop_fitted',cfg.product.emergency_stop_fitted);
    result=plel_validation_result('PLEL R1 product interface',s,value,true,true, ...
        'DESIGN_TARGET','R1 product strategy; obsolete R0 UI removed from active BOM',false, ...
        'Product interface definition closed for PCB design');
end
