function result = validate_thermal(cfg)
%VALIDATE_THERMAL Apply the shared-heatsink analytical chain.
    o=cfg.operating; t=cfg.thermal; ib=o.imax_A/o.mosfet_count;
    vds=o.vin_max_V-o.imax_A*o.shunt_ohm-ib*o.ballast_ohm;
    pmos=o.mosfet_count*vds*ib; p_sink=pmos;
    tsink=o.ambient_example_C+p_sink*t.rsa_target_K_W;
    tj=tsink+vds*ib*(cfg.datasheet.mosfet_rthetaJC_K_W+t.rcs_design_K_W);
    value=struct('Pload_W',o.vin_max_V*o.imax_A,'Pmosfet_W',pmos, ...
        'Pballast_W',o.mosfet_count*ib^2*o.ballast_ohm,'Pshunt_W',o.imax_A^2*o.shunt_ohm, ...
        'Psink_W',p_sink,'Tsink_C',tsink,'Tj_C',tj);
    result=plel_validation_result('Shared heatsink thermal chain','CONDITIONAL',value, ...
        t.junction_target_C,t.junction_target_C-tj,'CALCULATED', ...
        'Source §§18–19; RthetaSA/RthetaCS are design/example values, not measured assembly data',true, ...
        'Exact heatsink/TIM/airflow and physical temperatures remain open');
end
