function result = validate_power_tree(cfg)
%VALIDATE_POWER_TREE Calculate source illustrative regulator losses separately from final loads.
    i5=0.15; vin=cfg.operating.vin_max_V;
    value=struct('architecture','VIN -> 5 V regulator -> 3.3 V LDO', ...
        'illustrative_I5V_A',i5,'illustrative_I3V3_A',i5, ...
        'illustrative_P5V_W',(vin-5)*i5,'illustrative_P3V3_W',(5-3.3)*i5, ...
        'final_load_budget','TBD');
    result=plel_validation_result('Low-voltage power tree','CONDITIONAL',value, ...
        'Worst-case load currents, dropout and thermal margin',NaN,'CALCULATED', ...
        'Source PDF §27; 150 mA is explicitly an illustrative assumption',true, ...
        'Exact LDO, ESP32/OLED/fan loads and regulator thermal path required');
end
