function result = validate_loop_design(cfg)
%VALIDATE_LOOP_DESIGN Define a conservative design-level control-loop region.
% This is not an assembled-loop stability claim.
    f_filter=159; f_cross=25; plant_pole=5000; amp_pole=cfg.datasheet.lm_gbw_Hz;
    phase_lag=atan(f_cross/f_filter)+atan(f_cross/plant_pole)+atan(f_cross/amp_pole);
    phase_margin=180-phase_lag*180/pi;
    value=struct('topology','DAC setpoint -> LM358 error stage -> gated MOSFET bank -> shunt -> INA180A3 -> filtered feedback', ...
        'feedback_filter_Hz',f_filter,'design_crossover_Hz',f_cross, ...
        'assumed_plant_pole_Hz',plant_pole,'LM358_pole_bound_Hz',amp_pole, ...
        'illustrative_phase_at_assumed_frequency_deg',phase_margin, ...
        'model_matches_circuit',false, ... ...
        'compensation','Keep crossover <=25 Hz; retain 10 kohm/100 nF current filter; add 100 pF-1 nF local Miller/feedback capacitor after schematic review', ...
        'hardware_measurement','Inject swept perturbation at setpoint and measure gate/current response with differential probes');
    result=plel_validation_result('Control-loop design approach','BLOCKED',value,45, ...
        phase_margin-45,'CALCULATED/DESIGN_TARGET', ...
        'Conservative first-order design envelope; MOSFET gm and parasitics require assembled Bode measurement',true, ...
        'Assumed 25 Hz is not a calculated unity-gain crossover; no component-matched controller/plant transfer function is defined');
end
